#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.138                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = g++.exe
WINDRES = windres.exe

INC =  -I$(SFML_INCLUDE)
CFLAGS =  -Wall -DSFML_DYNAMIC
RESINC = 
LIBDIR =  -L$(SFML_LIB)
LIB =  -lopengl32
LDFLAGS = 

INC_DEBUG =  $(INC)
CFLAGS_DEBUG =  $(CFLAGS) -std=c++11 -g
RESINC_DEBUG =  $(RESINC)
RCFLAGS_DEBUG =  $(RCFLAGS)
LIBDIR_DEBUG =  $(LIBDIR) -L$(SFML_LIB)
LIB_DEBUG = $(LIB) -lsfml-graphics-d -lsfml-window-d -lsfml-system-d
LDFLAGS_DEBUG =  $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\Raytracer.exe

INC_RELEASE =  $(INC)
CFLAGS_RELEASE =  $(CFLAGS) -O2
RESINC_RELEASE =  $(RESINC)
RCFLAGS_RELEASE =  $(RCFLAGS)
LIBDIR_RELEASE =  $(LIBDIR) -L$(SFML_LIB)
LIB_RELEASE = $(LIB) -lsfml-graphics -lsfml-window -lsfml-system
LDFLAGS_RELEASE =  $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\Raytracer.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\raytri.o $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\Vector.o $(OBJDIR_DEBUG)\\Triangle.o $(OBJDIR_DEBUG)\\Sphere.o $(OBJDIR_DEBUG)\\Scene.o $(OBJDIR_DEBUG)\\Renderer.o $(OBJDIR_DEBUG)\\RenderObj.o $(OBJDIR_DEBUG)\\Raytracer.o $(OBJDIR_DEBUG)\\Raymath.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\raytri.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\Vector.o $(OBJDIR_RELEASE)\\Triangle.o $(OBJDIR_RELEASE)\\Sphere.o $(OBJDIR_RELEASE)\\Scene.o $(OBJDIR_RELEASE)\\Renderer.o $(OBJDIR_RELEASE)\\RenderObj.o $(OBJDIR_RELEASE)\\Raytracer.o $(OBJDIR_RELEASE)\\Raymath.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\raytri.o: raytri.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c raytri.c -o $(OBJDIR_DEBUG)\\raytri.o

$(OBJDIR_DEBUG)\\main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\Vector.o: Vector.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Vector.cpp -o $(OBJDIR_DEBUG)\\Vector.o

$(OBJDIR_DEBUG)\\Triangle.o: Triangle.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Triangle.cpp -o $(OBJDIR_DEBUG)\\Triangle.o

$(OBJDIR_DEBUG)\\Sphere.o: Sphere.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Sphere.cpp -o $(OBJDIR_DEBUG)\\Sphere.o

$(OBJDIR_DEBUG)\\Scene.o: Scene.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Scene.cpp -o $(OBJDIR_DEBUG)\\Scene.o

$(OBJDIR_DEBUG)\\Renderer.o: Renderer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Renderer.cpp -o $(OBJDIR_DEBUG)\\Renderer.o

$(OBJDIR_DEBUG)\\RenderObj.o: RenderObj.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c RenderObj.cpp -o $(OBJDIR_DEBUG)\\RenderObj.o

$(OBJDIR_DEBUG)\\Raytracer.o: Raytracer.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Raytracer.cpp -o $(OBJDIR_DEBUG)\\Raytracer.o

$(OBJDIR_DEBUG)\\Raymath.o: Raymath.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Raymath.cpp -o $(OBJDIR_DEBUG)\\Raymath.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)

before_release: 
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\raytri.o: raytri.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c raytri.c -o $(OBJDIR_RELEASE)\\raytri.o

$(OBJDIR_RELEASE)\\main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\Vector.o: Vector.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Vector.cpp -o $(OBJDIR_RELEASE)\\Vector.o

$(OBJDIR_RELEASE)\\Triangle.o: Triangle.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Triangle.cpp -o $(OBJDIR_RELEASE)\\Triangle.o

$(OBJDIR_RELEASE)\\Sphere.o: Sphere.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Sphere.cpp -o $(OBJDIR_RELEASE)\\Sphere.o

$(OBJDIR_RELEASE)\\Scene.o: Scene.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Scene.cpp -o $(OBJDIR_RELEASE)\\Scene.o

$(OBJDIR_RELEASE)\\Renderer.o: Renderer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Renderer.cpp -o $(OBJDIR_RELEASE)\\Renderer.o

$(OBJDIR_RELEASE)\\RenderObj.o: RenderObj.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c RenderObj.cpp -o $(OBJDIR_RELEASE)\\RenderObj.o

$(OBJDIR_RELEASE)\\Raytracer.o: Raytracer.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Raytracer.cpp -o $(OBJDIR_RELEASE)\\Raytracer.o

$(OBJDIR_RELEASE)\\Raymath.o: Raymath.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Raymath.cpp -o $(OBJDIR_RELEASE)\\Raymath.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

